const dictionary = {
        "kitap": "Okumak için kullanılan yazılı materyal.",
        "kalem": "Yazı yazmaya yarayan araç.",
        "bilgisayar": "Bilgi işleyen elektronik cihaz.",
        "ev": "İnsanların yaşadığı yer.",
        "defter": "Not almak için kullanılan araç.",
        "telefon": "İletişim için kullanılan cihaz.",
        "masa": "Üzerinde çalışmak veya yemek yemek için kullanılan mobilya.",
        "atık": "Doğal çevreye zarar veren ya da yeniden kullanılamayan materyaller.",
        "akıllı şehirler": "Teknolojik altyapı kullanarak şehir yaşamını daha verimli hale getiren şehirler.",
        "akıllı tarım": "Teknolojik araçlar ve sistemlerle yapılan tarım uygulamaları.",
        "akıllı su şehri": "Su kaynaklarını daha verimli kullanmak için teknoloji ile yönetilen şehirler.",
        "aşırı hava olayları": "Sıklığı artan ve şiddetli hale gelen hava olayları.",
        "aşırı tüketim": "Kaynakların sürdürülebilir sınırların çok üzerinde kullanılması.",
        "adaptasyon": "İklim değişikliğine uyum sağlamak için yapılan değişiklikler.",
        "antropojenik K.I.": "İnsan faaliyetlerinin çevre üzerinde yarattığı değişiklikler.",
        "azaltma": "İklim değişikliğine yol açan emisyonların azaltılması süreci.",
        "arktik salınım": "Kuzey Kutbu’ndaki iklim ve çevresel değişimlerin dünya üzerindeki etkileri.",
        "afet": "Doğal ya da insan kaynaklı büyük zarar veren olaylar.",
        "afet risk yönetimi": "Afetlerin etkilerini en aza indirmek için yapılan çalışmalar.",
        "ani iklim değişikliği": "Kısa bir süre içinde gerçekleşen ani iklimsel değişiklikler.",
        "arazi istilası": "İnsan yerleşimlerinin ormanlık alanları yok ederek yerleşim alanlarını büyütmesi.",
        "aşırı deniz seviyesi": "Deniz seviyelerinin olağandışı derecede yükselmesi.",
        "adil dönüşüm": "Çalışma alanlarındaki değişikliklerin toplumsal açıdan eşit ve adil şekilde yapılması.",
        "atık su yönetimi": "Atık suyun işlenmesi ve çevreye zarar vermeden yönetilmesi.",
        "azot döngüsü": "Azotun doğadaki hareketi ve yeniden kullanım döngüsü.",
        "başa çıkma": "Zorluklarla başa çıkmak için alınan önlemler ve stratejiler.",
  "başa çıkma kapasitesi": "Bir sistemin veya toplumun stresle başa çıkabilme yeteneği.",
  "biyoçeşitlilik": "Bir ekosistemdeki farklı türlerin çeşitliliği.",
  "biyoenerji": "Biyolojik kaynaklardan elde edilen enerji.",
  "biyokütle": "Organik materyallerin enerji üretimi için kullanılması.",
  "biyosfer": "Yeryüzündeki tüm yaşam alanlarını kapsayan ekosistem.",
  "biyoyakıt": "Bitkisel veya hayvansal kaynaklardan elde edilen yakıt.",
  "bir buçuk derece": "Paris Anlaşması'nda belirtilen, küresel sıcaklık artışının 1.5°C'yi geçmemesi gerektiği hedef.",
  "birleşmiş milletler iklim değişikliği çerçeve sözleşmesi": "BM'nin iklim değişikliği ile mücadele için oluşturduğu uluslararası anlaşma.",
  "belirsizlik": "Sonuçların veya olayların tahmin edilememesi durumu.",
  "buz erimesi": "Küresel ısınmanın bir sonucu olarak buzulların erimesi.",
  "bağıl deniz seviyesi": "Deniz seviyesinin bir referans noktasına göre değişimi.",
  "cop": "İklim değişikliği ile mücadele için yapılan uluslararası konferanslar.",
  "çevresel göç": "İklim değişikliği ve çevresel faktörlerin neden olduğu göçler.",
  "çarpık kentleşme": "Planlı ve sürdürülebilir olmayan kentleşme.",
  "çölleşme": "Toprağın verimliliğini kaybederek çölleşen alanlara dönüşmesi.",
  "deniz seviyesinin değişimi": "İklim değişikliği nedeniyle deniz seviyesinin yükselmesi veya düşmesi.",
  "düşük karbonlu kalkınma": "Karbon emisyonlarını en aza indiren kalkınma modelleri.",
  "dünya saati": "Çevreye dikkat çekmek amacıyla yapılan, her yıl düzenlenen etkinlik.",
  "dönüşüm": "Bir sistemin ya da yapının daha sürdürülebilir hale getirilmesi süreci.",
  "deniz yüzey sıcaklığı": "Okyanus yüzeyinin sıcaklığı, iklim değişikliğini etkileyen bir faktördür.",
  "dezavantajlı gruplar": "İklim değişikliğinden en çok etkilenen, güçsüz topluluklar.",
  "dış etkenler": "Bir sistemin ya da olayın dışında kalan ve etki yaratan faktörler.",
  "dirençlilik": "Bir toplumun veya ekosistemin stres faktörlerine karşı dayanıklılığı.",
  "ekoloji": "Canlılar ile çevrelerinin etkileşimlerini inceleyen bilim dalı.",
  "ekosistem": "Bir bölgede bulunan tüm canlıların ve çevrenin oluşturduğu etkileşimli sistem.",
  "ekolojik ayak izi": "Bir bireyin veya toplumun çevreye olan etkisinin ölçülmesi.",
  "ekolojik denge": "Ekosistem içinde, canlılar ve çevre arasında uyumlu bir denge.",
  "enerji verimliliği": "Daha az enerji kullanarak aynı miktarda fayda sağlama.",
  "emisyonlar": "Atmosfere salınan gazlar, genellikle sera gazları.",
  "ekosistem temelli uyum": "Ekosistem hizmetlerinden yararlanarak iklim değişikliğine uyum sağlama.",
  "erken uyarı sistemi": "Afetleri veya tehlikeleri önceden tespit edip, alarm veren sistem.",
  "etkilenebilirlik": "Bir sistemin iklim değişikliğinden ne kadar etkileneceği.",
  "eş fayda": "Bir tarafın faydası artarken, diğer tarafın zarar görmediği durum.",
  "ekolojik okuryazarlığı": "Doğal çevre ve ekosistemler hakkında bilgi sahibi olma.",
  "fosil yakıt": "Karbon bazlı enerji kaynakları, kömür, petrol ve doğalgaz.",
  "fenoloji": "Doğal olayların (örneğin bitkilerin çiçek açması) zamanlaması üzerine yapılan inceleme.",
  "fırsat maliyeti": "Bir seçenek yerine başka bir seçenek seçildiğinde kaybedilen değer.",
  "fırtına dalgası": "Yoğun ve şiddetli rüzgarlarla birlikte gelen fırtına türü.",
  "güneş enerjisi": "Güneş ışığından elde edilen enerji.",
  "gelişmekte olan ülkeler": "Ekonomik olarak kalkınma aşamasında olan ülkeler.",
  "geri dönüşüm": "Kullanılmış malzemelerin tekrar kullanılabilir hale getirilmesi.",
  "güneş tarlaları": "Güneş enerjisi üretimi için kurulan büyük ölçekli güneş panelleri alanları.",
  "gıda israfı": "Üretilen gıdanın tüketilmeden atılması.",
  "gıda güvenliği": "Herkesin yeterli ve sağlıklı gıdaya erişimi.",
  "gıdaya erişim": "Kişilerin sağlıklı gıdalara ulaşabilme durumu.",
  "günlük sıcaklık farkı": "Bir gün içindeki en yüksek ve en düşük sıcaklık arasındaki fark.",
  "hava kirliliği": "Atmosferdeki zararlı gaz ve partiküllerin yoğunluğu.",
  "hassasiyet": "Bir sistemin veya bireyin dışsal değişimlere gösterdiği tepki.",
  "hava tahmini": "Hava durumu hakkında yapılan öngörüler.",
  "hidrolojik döngü": "Su buharlaşması, yağış ve suyun yer altına inmesi süreçlerini kapsayan su döngüsü.",
  "iklim": "Bir bölgedeki uzun süreli hava koşulları ve atmosfer olayları.",
  "iklim değişikliği": "İklim sistemindeki uzun dönemli değişiklikler.",
  "iklim değişikliği taahhütü": "Ülkelerin, küresel ısınmayı sınırlamak amacıyla üstlendikleri hedefler.",
  "iklim değişkenliği": "İklimdeki zaman içindeki doğal değişiklikler.",
  "iklim mühendisliği": "İklim değişikliğini kontrol altına almak amacıyla yapılan teknolojik müdahaleler.",
  "iklim senaryosu": "Farklı iklim değişikliği senaryolarına dayalı gelecekteki iklim tahminleri.",
  "iklim sistemi": "Atmosfer, okyanuslar, buzullar, bitki örtüsü ve diğer iklim etkenlerinden oluşan sistem.",
  "iklim tahmini": "İklim ile ilgili geleceğe yönelik yapılan tahminler.",
  "iklim yönetişimi": "İklim değişikliği ile mücadele etmek için yönetim ve politika stratejileri.",
  "iklim değiştiren kirleticiler": "Sera gazları gibi iklim değişikliğine yol açan kirletici maddeler.",
  "iklime alışma": "İklim değişikliğine uyum sağlamak ve adaptasyon stratejileri geliştirmek.",
  "insan kaynaklı emisyon": "Fosil yakıtlar ve diğer faaliyetler sonucu ortaya çıkan sera gazı emisyonları.",
  "iklim değişikliği kaygısı": "İklim değişikliğinin gelecekteki etkileri konusunda duyulan endişe.",
  "iklim dönüşümü": "İklim değişikliği ile mücadele etmek ve toplumsal yapıları dönüştürmek.",
  "iklim adaleti": "İklim değişikliğinden etkilenen toplumların haklarının korunması.",
  "iklim aktivisti": "İklim değişikliğine karşı farkındalık yaratmak için mücadele eden kişi.",
  "iklim okuryazarı": "İklim değişikliği ve çevre sorunları hakkında bilgi sahibi olan birey.",
  "istilacı tür": "Doğal ortama zarar vererek, yerli türlerin yerini alan yabancı türler.",
  "ipcc": "Hükümetler arası İklim Değişikliği Paneli, iklim değişikliği üzerine yapılan bilimsel değerlendirmeleri yöneten uluslararası kuruluş.",
      "ısı kapasitesi": "Bir maddenin sıcaklık değişimine karşı gösterdiği direnç, belirli bir ısıyı emme veya salma kapasitesi.",
  "ısıl genleşme": "Bir maddenin ısı ile genişlemesi, sıcaklık arttıkça moleküllerinin daha geniş bir alana yayılması.",
  "küresel ısınma": "Atmosferdeki sera gazlarının birikmesiyle dünya yüzeyinin ortalama sıcaklığının artması.",
  "karbon": "Kimyasal bir element, organik bileşiklerin temel yapı taşıdır, karbon bazlı yaşam formları bulunur.",
  "kuraklık": "Uzun süreli su eksikliği nedeniyle toprakların kuruması, tarım ve su kaynaklarını tehdit etmesi.",
  "karbon vergisi": "Fosil yakıt kullanımından kaynaklanan karbon salınımlarını azaltmaya yönelik, karbon emisyonları üzerinden uygulanan vergi.",
  "karbon döngüsü": "Doğadaki karbonun, atmosfer, okyanuslar ve kara ekosistemleri arasında sürekli olarak dönüşümünü açıklayan süreç.",
  "karbon denkleştirme": "Bir kişi veya kuruluşun yaydığı karbon emisyonlarının, doğaya geri kazandırılması için yapılan faaliyetler.",
  "karbon ayak İzi": "Bir kişinin, ailenin, kuruluşun veya ürünün yaşam döngüsü boyunca yaydığı karbon salınımlarının toplamı.",
  "kontrol edilemeyen orman yangını": "Doğal ya da insan kaynaklı başlayan ve yayılmasını engellemekte zorlanan orman yangınları.",
  "klimatoloji": "İklim, atmosfer koşulları ve hava olayları üzerine yapılan bilimsel çalışma.",
  "karbon nötr": "Bir kişinin, kuruluşun veya ülkenin karbon emisyonlarını sıfırlamak amacıyla denkleştirilmesi durumudur.",
  "karbon salınımı": "Karbon dioksit ve diğer sera gazlarının atmosfere salınması.",
  "kyoto protokolü": "Birleşmiş Milletler İklim Değişikliği Çerçeve Sözleşmesi’ne taraf ülkelerinin sera gazı emisyonlarını azaltmaya yönelik anlaşma.",
  "karbon kredisi": "Bir ton karbondioksit emisyonunu dengelemek için elde edilen hak, genellikle çevre dostu projelerle elde edilir.",
  "küresel karbon bütçesi": "Dünyanın tüm sera gazı emisyonlarının bir araya getirilerek, karbon salınımlarını dengelemek için belirlenen toplam miktar.",
  "kapasite geliştirme": "Toplumların ve ülkelerin, çevresel ve ekonomik krizlere karşı direnç oluşturabilecek yeteneklerini artırma süreci.",
  "karbon tutma": "Atmosferdeki karbondioksitin doğrudan yakalanması ve depolanması.",
  "karbon yakalama ve tutma": "Fosil yakıt kullanımından kaynaklanan karbondioksit emisyonlarının, havaya salınmadan önce yakalanıp yer altına depolanması.",
  "karbon yutakları": "Karbon dioksiti emen ve depolayan doğal ve yapay sistemler, örneğin ormanlar, okyanuslar.",
  "karbondioksit": "Fosil yakıtların yanması sonucu ortaya çıkan sera gazlarından biri, atmosferdeki önemli bir iklim değişikliği kaynağı.",
  "karbonsuzlaşma": "Fosil yakıt kullanımının sona erdirilmesi, karbon emisyonlarının sıfırlanması amacıyla yapılan çabalar.",
  "kent isı adası": "Şehirlerde, çevre kırsal alanlara göre daha yüksek sıcaklıkların görülmesi durumu.",
  "kendiliğinden uyum": "Bir toplumun, herhangi bir dış yardım olmadan, iklim değişikliği etkilerine adapte olması.",
  "kıtlık": "Su ve gıda gibi temel kaynakların yetersizliği.",
  "kıyı alan baskısı": "Kıyı bölgelerinde nüfus artışı, turizm ve endüstriyel faaliyetler nedeniyle doğal alanların bozulması.",
  "konveksiyon": "Isının sıvılar veya gazlar aracılığıyla taşınması, sıcak hava yükselirken soğuk hava aşağı iner.",
  "kriyosfer": "Dünyadaki buzulları ve donmuş alanları ifade eder.",
  "kurak alan": "Su kaynakları ve yağışın çok az olduğu, tarım için verimli olmayan bölgeler.",
  "küresel iklim modeli": "Dünya çapında iklim değişikliklerini tahmin etmek için kullanılan bilgisayar destekli matematiksel modeller.",
  "küresel ortalama yüzey sıcaklığı": "Dünya yüzeyindeki sıcaklıkların zaman içinde ölçülen ortalama değeri.",
  "kuzey atlantik salınımı": "Okyanus akıntıları ve atmosfer koşullarındaki değişikliklerin küresel iklim üzerindeki etkilerini tanımlar.",
  "limit aşım günü": "Bir ülkenin veya dünyanın yıllık ekolojik kapasitesini tükettikleri tarih, yani doğal kaynakları tüketme hızını gösterir.",
  "meton gazı": "Atmosferde bulunan ve iklim değişikliğine neden olabilen, insan kaynaklı sera gazlarından biridir.",
  "müsilaj": "Denizlerde görülen, planktonların aşırı büyümesi sonucu suyun üst kısmında oluşan organik madde birikintisi.",
  "minimal yaşam": "Tüketim alışkanlıklarının en aza indirildiği, doğal kaynakların verimli kullanıldığı yaşam tarzı.",
  "mercan ağarması": "Okul mercanlarının beyazlaşması, çoğunlukla sıcaklık artışlarından dolayı meydana gelir ve mercanların sağlığını tehdit eder.",
  "mikro iklim": "Bir bölgedeki hava koşullarının, çevresindeki büyük alanlara göre farklılık gösterdiği, yerel iklim özellikleridir.",
  "minimum oksijen bölgesi": "Okyanuslarda, oksijen seviyesinin en düşük olduğu alanlardır, bu bölgelerde deniz yaşamı sınırlıdır.",
  "okyanus asitlenmesi": "Okyanusların, atmosferdeki karbondioksitin çözünmesiyle asidik hale gelmesi.",
  "ormansızlaşma": "Ormanların yok olması veya azalması, çoğunlukla insan etkinlikleri nedeniyle meydana gelir.",
  "ozan tabakasının delinmesi": "Atmosferdeki ozon tabakasının incelmesi, zararlı UV ışınlarının Dünya yüzeyine ulaşmasına neden olur.",
  "ortalama deniz seviyesi": "Dünya denizlerinin yüzeyindeki ortalama yükseklik, iklim değişiklikleri nedeniyle yükselmesi riski taşır.",
  "ozon": "Atmosferde bulunan, UV ışınlarını emen gaz, ozon tabakası Dünya'yı zararlı ışınlardan korur.",
  "öngörülebilirlik": "Bir olayın, durumun veya koşulun gelecekteki yönünün tahmin edilebilirliği.",
  "ölü bölgeler": "Okyanuslarda oksijen seviyesi çok düşük olan, deniz yaşamının var olamadığı alanlar.",
  "partiküller": "Havadaki küçük katı veya sıvı maddeler, çevresel kirliliğe neden olabilir.",
  "permafrost": "Yılın büyük kısmında donmuş kalan toprak veya kaya, iklim değişikliği ile eriyebilir.",
  "plastik ayak İzi": "Bir kişinin veya kuruluşun plastik kullanımının çevreye etkisi.",
  "paris iklim antlaşması": "2015 yılında Paris'te imzalanan ve küresel sıcaklık artışını 2°C ile sınırlamayı amaçlayan anlaşma.",
  "petrol sızıntısı": "Denizlere veya kara yüzeyine petrolün kazara veya bilinçli olarak dökülmesi.",
  "plakton": "Denizlerde bulunan küçük organizmalar, deniz ekosisteminin temelini oluştururlar.",
  "rüzgar enerjisi": "Rüzgarın hareketinden elde edilen enerji, yenilenebilir enerji kaynaklarından biridir.",
  "rüzgar tribünü": "Rüzgarın kinetik enerjisini elektrik enerjisine dönüştüren makineler.",
  "radyasyon": "Enerji dalgalarının yayılması, özellikle güneşten gelen ışınlar iklimi etkileyebilir.",
  "risk algısı": "Bir tehlike veya tehdidin ciddiyetini, etkisini anlamak ve değerlendirmek.",
  "risk yönetimi": "Risklerin tanımlanması, değerlendirilmesi ve minimize edilmesi için yapılan planlama ve eylemler.",
  "sanayi devrimi": "18. yüzyılın sonlarından itibaren, makinelerin kullanılmasıyla üretim yöntemlerinde büyük değişikliklerin yaşandığı dönem.",
  "sanayileşme öncesi": "Sanayi devriminden önceki dönem, doğal kaynakların daha sınırlı ve tarıma dayalı ekonomiler.",
  "sera etkisi": "Atmosferdeki sera gazlarının, gezegenin yüzeyinde ısınmaya neden olan etkileşim.",
  "su ayak İzi": "Bir kişinin veya ürünün yaşam döngüsü boyunca kullandığı toplam su miktarı.",
  "sürdürülebilirlik": "Bugünün ihtiyaçlarını, gelecek nesillerin ihtiyaçlarını tehlikeye atmadan karşılayabilme yeteneği.",
  "sera gazı": "Atmosferdeki, iklim değişikliğine neden olan gazlar, örneğin karbondioksit, metan.",
  "sürdürülebilir kalkınma": "Ekonomik gelişmeyi, çevreye zarar vermeden ve toplumsal eşitsizlikleri azaltarak sürdürme yaklaşımı.",
  "sera gazı yutağı": "Karbon dioksit gibi sera gazlarını emen doğal sistemler, örneğin ormanlar.",
  "sıfır atık": "Atık üretimini tamamen ortadan kaldırmaya yönelik bir yaşam tarzı.",
  "su kıtlığı": "Su kaynaklarının, artan talebi karşılayamayacak seviyeye düşmesi.",
  "sanayileşme": "Üretim süreçlerinin makinelerle yapıldığı, iş gücünün daha verimli kullanıldığı bir ekonomik döneme geçiş.",
  "su döngüsü": "Su buharlaşması, yağış ve yer yüzeyindeki akış yoluyla suyun sürekli olarak döngüsel hareketi.",
  "sıcak hava dalgası": "Sıcaklıkların normalin üzerinde seyrettiği uzun süreli hava durumu fenomeni.",
  "sosyoekonomik senaryo": "Bir bölgedeki sosyal ve ekonomik koşulların gelecekteki durumu üzerine yapılan tahminler.",
  "stratosfer": "Atmosferin, troposferin üstündeki katmanı, ozon tabakasını içerir.",
  "taşkın": "Aşırı yağış veya eriyen kar nedeniyle nehirlerin taşıp çevresini etkilemesi.",
  "termoklin": "Okyanuslardaki sıcaklık değişiminin hızlı olduğu katman.",
  "toplu etki": "Birden fazla faktörün bir araya gelip çevresel bir etki oluşturması.",
  "toplum temelli uyum": "Toplumların, yerel bilgilere ve kaynaklara dayalı olarak iklim değişikliğine karşı uyum sağlama stratejileri.",
  "tropikal siklon": "Yüksek sıcaklıkta okyanuslarda oluşan ve güçlü rüzgarlar ile yağışlar getiren fırtına.",
  "troposfer": "Atmosferin en alt katmanı, hava olaylarının çoğu burada gerçekleşir.",
  "tsunami": "Deniz altı depremleri veya volkanik patlamalar sonucu oluşan büyük dalgalar.",
  "uyum": "İklim değişikliğine karşı doğal ve toplumsal sistemlerin adapte olma süreci.",
  "uzay kirliliği": "Uzaya gönderilen uydular, roketler ve diğer cihazların, atmosferde ve uzayda bıraktığı kalıntılar.",
  "uyarlanabilir kapasite": "Bir topluluğun, değişen koşullara uyum sağlama yeteneği.",
  "uyum eşiği": "Toplumların, iklim değişikliğine karşı etkili bir şekilde uyum sağlamak için ihtiyaç duyduğu minimum seviyeler.",
  "üretim- tüketim dengesi": "Doğal kaynakların kullanımı ve insanların tüketimi arasındaki dengeyi sağlama çabası.",
  "verimlilik": "Kaynakların daha az tüketilerek daha fazla çıktı üretme kapasitesi.",
  "verimli tarım alanları": "Tarım ürünlerinin yüksek verimle yetiştirildiği alanlar.",
  "yenilenebilir enerji": "Doğal kaynaklardan elde edilen ve sürekli olarak yenilenen enerji türleri (güneş, rüzgar, hidro vb.).",
  "yenilenemez enerji": "Sınırlı miktarda olan ve tükenme riski taşıyan enerji kaynakları (petrol, kömür vb.).",
  "yeşil ekonomi": "Çevre dostu, sürdürülebilir üretim ve tüketim alışkanlıkları ile desteklenen ekonomik model.",
  "yerel ürün": "Bir bölgeye özgü ve yerel üreticiler tarafından üretilen tarım veya sanayi ürünleri.",
  "yoksulluk": "Temel ihtiyaçların karşılanamaması nedeniyle yaşanan sosyal ve ekonomik zorluk.",
  "yüzey sıcaklığı": "Dünya yüzeyinin sıcaklığı, iklim değişikliğine dair önemli bir gösterge.",
  "zehirli maddeler": "Canlılar için tehlike yaratabilecek, zararlı kimyasal bileşikler."
}
      
  const searchBox = document.getElementById("search-box");
  const resultDiv = document.getElementById("result");
  
  searchBox.addEventListener("input", function () {
    const query = searchBox.value.toLowerCase();
    if (dictionary[query]) {
      resultDiv.textContent = `${query}: ${dictionary[query]}`;
    } else if (query === "") {
      resultDiv.textContent = "";
    } else {
      resultDiv.textContent = "Kelime bulunamadı.";
    }
  });  